### ISSUE TITLE
Make a Factory service for Adapter and Pagination class

### ISSUE THREAD

**Issue by ruscon** [whiteoctober/WhiteOctoberPagerfantaBundle#105]
How about to make a service as the wrapper class ? 

native
```php
$pagination = new Pagerfanta(new DoctrineORMAdapter($queryBuilder));
$pagination->setMaxPerPage($maxPerPage);
```
service
```php
$pagination = $this->container->get('white_october_pagerfanta.doctrine_orm')
    ->setQueryBuilder($queryBuilder)
    ->getPagination()
;

$pagination->setMaxPerPage($maxPerPage);
```
or with setArguments
```php
$pagination = $this->container->get('white_october_pagerfanta.doctrine_dbal')
    ->setArguments($queryBuilder, $countQueryBuilderModifier)
    ->getPagination()
;

$pagination->setMaxPerPage($maxPerPage);
```

and default service configuration
```yml
#app/config/config.yml;
white_october_pagerfanta:
    default_adapter: doctrine_orm
```
using
```php
$pagination = $this->container->get('white_october_pagerfanta.default')
    ->setArguments($queryBuilder)
    ->getPagination()
;

$pagination->setMaxPerPage($maxPerPage);
```
etc...

**Comment by pablodip** [comment]
What's the advantage? :)

**Comment by ruscon** [comment]
We can do something like this:
```yml
#app/config/config.yml;
white_october_pagerfanta:
    default_adapter: doctrine_orm # doctrine_dbal | array | Some\ Adapter\CustomAdaper
    max_per_page: 10
    page_range: 5 # default page range used in pagination control
    may_be_some_other_param: ~
```
