### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by rlavolee** [whiteoctober/WhiteOctoberPagerfantaBundle#107]
Hi,

First, thank you all for this nice bundle.
I faced a problem of duplicate content with the pager. I'v got two routes about product listings because of SEO beliefs (example below).  

 ```yaml
product_home:
   pattern: /products/
   methods: GET
   defaults:
      _controller: ProductBundle:plop:index
      page: 1

product_home_page:
   pattern: /products/page-{page}
   methods: GET
   defaults:
      _controller: ProductBundle:plop:index
      page: 1
```

As you can guess `/products/` and `/products/page-1` display the same page and so, are seen as duplicate content. 
I've solved it by passing the `product_home` route as argument to the Pagerfanta Twig extension and use this to generate the route for first page.
Does it worth a pull request or is it too specific to integrate this possibility into the bundle ?
