### ISSUE TITLE
Previous and Next messages with Bootstrap 3 view

### ISSUE THREAD

**Issue by gjuric** [whiteoctober/WhiteOctoberPagerfantaBundle#117]
What is the simplest way to set Bootstrap 3 template as default and provide custom strings for next / previous?

If I use the OptionableView to pass in previous & next messages I loose the Bootstrap output.

**Comment by gjuric** [comment]
To answer my own question:

In your services.yml create a new service:

```yaml
    pagerfanta.view.custom_view:
        class: Pagerfanta\View\OptionableView
        arguments:
            - @pagerfanta.view.twitter_bootstrap3
            - { proximity: 2, prev_message: ← Prethodna, next_message: Sljedeća → }
        public: false
        tags: [{ name: pagerfanta.view, alias: custom_view }]
```

And than in your config.yml

```yaml
white_october_pagerfanta:
    default_view: custom_view
```

The name of the view is what you put in the alias tag in the last line of the service definition.

This way you do not have to activate the translation in your Symfony app if you are only using one language and you can still customize the previous and next messages.
