### ISSUE TITLE
Pagerfanta generate route empty for 1st page

### ISSUE THREAD

**Issue by pmithrandir** [whiteoctober/WhiteOctoberPagerfantaBundle#134]
Hello,

I have the following route defined : 
```
JaiUneIdeeSiteBundle_homepage:
    pattern:  /
    defaults: {_controller: JaiUneIdeeSiteBundle:Page:index, page:1, page_news:1 }
JaiUneIdeeSiteBundle_homepage_pagination:
    pattern:  /{page}/{page_news}/{requester}
    defaults: {_controller: JaiUneIdeeSiteBundle:Page:index, page:1, page_news:1 }
    requirements:
        page: \d+
        page_news: \d+
```
Of course, I use the second one to paginate.

Since my last upgrade
```
  - Removing white-october/pagerfanta-bundle (v1.0.2)
  - Installing white-october/pagerfanta-bundle (v1.0.5)

```
I 'm getting a strange behaviour.
The first page url is now looking this way : 
http://jaiuneidee.dev/app_dev.php/1//news

when it was before looking this way : 
https://jaiuneidee.dev/app_dev.php/1/1/news

Consequence, I have to change the config/framework/router/strict_requirements to null to make it works, by ignoring the validation \d+.

Any idea why the first page is not 1 anymore, or how I could correct that ?

I got the same error on the 2 paginator present on this page, but not on the one on another page where only 1 pagination is applied.

Best regards,
Pierre
