### ISSUE TITLE
previous_message no effect

### ISSUE THREAD

**Issue by KonRan153** [whiteoctober/WhiteOctoberPagerfantaBundle#94]
Hi,

I can't change the previous message.. No problem with next it change perfectly but previous...

```
pagerfanta.view.test:
    class: Pagerfanta\View\OptionableView
    arguments:
        - @pagerfanta.view.twitter_bootstrap
        - { previous_message: &#10096, next_message: &#10097 }
    public: false
    tags: [{ name: pagerfanta.view, alias: test }]
```

Did i forget something ?
