### ISSUE TITLE
how to add a custom twig template ?

### ISSUE THREAD

**Issue by ibasaw** [whiteoctober/WhiteOctoberPagerfantaBundle#98]
I would like to override the default template, and custom it with a template.html.twig file in my root views folder

Can't find anything on internet about it...

**Comment by KnutSv** [comment]
This does not really answer the question. I've spent countless hours trying and failing to create a custom template. If it is actually possible does anyone have a working example that we can look at?

From what I've gathered I can add a `pagerfanta.yml` file in my bundle's `Resources/config` folder:
```
services:
    pagerfanta.view.{{my_view}}:
        class: {{Company}}\{{Bundle}}\View\{{MyView}}View
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]
```

I then add a {{MyView}}View.php-file in my bundles `View` folder:
```
<?php
namespace Pagerfanta\View;

use {{Company}}\{{Bundle}}\View\Template\{{MyView}}Template;

class {{MyView}}View extends DefaultView
{
    protected function createDefaultTemplate()
    {
        return new {{MyView}}Template();
    }

    protected function getDefaultProximity()
    {
        return 3;
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return '{{my_view}}';
    }
}
```

And then in my bundles `View/Template` folder, I add a fike {{MyView}}Template.php
```
<?php

namespace Pagerfanta\View;

/**
 * @author Pablo Díez <pablodip@gmail.com>
 */
class {{MyView}}Template extends Template
{
    static protected $defaultOptions = array(
        ...
    );

   ...
}
```

In my template I try to include it like this:
```
{{ pagerfanta( pagerFolder, '{{my_view}}')}}
```

This code gives me the error:
``An exception has been thrown during the rendering of a template ("The view "{{my_view}}" does not exist.")``

Most of this is not really documented, which is why I've had to sniff around the source code and guess how it works. Would be great with a demo template.

**Comment by mirodav** [comment]
If anybody is looking for answer to ibasaw's question, here is how you use custom views with this bundle:

##### 1. Create View class (./src/Foo/BarBundle/View/MyView.php):
```php
namespace Foo\BarBundle\View;
use Pagerfanta\View\DefaultView;
use Foo\BarBundle\View\Template\MyTemplate;

class MyView extends DefaultView {
    protected function createDefaultTemplate() {
        return new MyTemplate();
    }

    protected function getDefaultProximity() {
        return 3;
    }

    /**
     * {@inheritdoc}
     */
    public function getName() {
        return 'my';
    }
}
```

##### 2. Create Template class (./src/Foo/BarBundle/View/Template/MyTemplate.php):
```php
<?php
namespace Foo\BarBundle\View\Template;

class MyTemplate extends \Pagerfanta\View\Template\Template {

// copy contents of class from  ./vendor/pagerfanta/pagerfanta/src/Pagerfanta/View/Template/TwitterBootstrapTemplate.php
// and adjust to your preferences

}
```

##### 3. Add your new view class as service (./src/Foo/BarBundle/Resources/config/services.yml):
```yml
services:
    pagerfanta.view.my:
        class: Foo\BarBundle\View\MyView
        public: false
        tags:
            - { name: 'pagerfanta.view', alias: 'my' }
```

##### 4. Use in your twig template:
```html
{{ pagerfanta(pager, 'my') }}
```
